/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.editor;

import javax.swing.JEditorPane;
import javax.swing.text.DefaultEditorKit;
import javax.swing.text.PlainDocument;
import javax.swing.text.StyledEditorKit;

/**
 *
 * @author ce
 */
public class EditorPane extends javax.swing.JPanel {

  /**
   * Creates new form JEditor
   */
  public EditorPane() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane2 = new javax.swing.JScrollPane();
    rowHeader = new javax.swing.JTextArea();
    jeditor_scroll = new javax.swing.JScrollPane();
    editor = new javax.swing.JEditorPane();

    rowHeader.setEditable(false);
    rowHeader.setBackground(new java.awt.Color(192, 192, 192));
    rowHeader.setColumns(1);
    rowHeader.setFont(editor.getFont());
    rowHeader.setRows(5);
    rowHeader.setText("1");
    rowHeader.setFocusable(false);
    jScrollPane2.setViewportView(rowHeader);

    setLayout(new java.awt.BorderLayout());

    editor.setFont(new java.awt.Font("Inconsolata", 0, 18)); // NOI18N
    jeditor_scroll.setViewportView(editor);
    editor.getDocument().putProperty(PlainDocument.tabSizeAttribute, 4);

    add(jeditor_scroll, java.awt.BorderLayout.CENTER);
    jeditor_scroll.setRowHeaderView(rowHeader);
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JEditorPane editor;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jeditor_scroll;
  private javax.swing.JTextArea rowHeader;
  // End of variables declaration//GEN-END:variables

  public JEditorPane getEditor() {
    return editor;
  }
}
