
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 01 00:29:41 CST 2013
//----------------------------------------------------

package compiler.bad;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int SETF = 62;
  public static final int KW_INTEGER = 19;
  public static final int FUNC_GET_BOOL = 68;
  public static final int FUNC_GET_F = 67;
  public static final int SI = 58;
  public static final int CREAR_POTENCIA = 40;
  public static final int ADDF = 38;
  public static final int FUNC_GET_LIBRE = 64;
  public static final int CREAR_ESTRATEGIA = 48;
  public static final int FUNC_GET_MUNICIONES = 63;
  public static final int MEDIUM = 44;
  public static final int PROC_SETF = 80;
  public static final int FIN_PARA = 57;
  public static final int NOT = 23;
  public static final int KW_BOOLEAN = 15;
  public static final int MULTI = 33;
  public static final int FUNC_ARMA_PROPIA = 73;
  public static final int FLOAT = 9;
  public static final int LOW = 43;
  public static final int BETHAN = 29;
  public static final int CREAR_ENEMIGO = 47;
  public static final int CREAR_IMAGEN = 39;
  public static final int HACER = 56;
  public static final int PARA = 53;
  public static final int COMA = 13;
  public static final int FUNC_GET_STR = 69;
  public static final int FIN_SI = 59;
  public static final int NERROR = 35;
  public static final int PROC_ASIGNAR_SALTO = 76;
  public static final int FUNC_GET_VAL = 66;
  public static final int LONG = 10;
  public static final int PLUS = 32;
  public static final int DISMINUIR = 55;
  public static final int PROC_GIRAR = 78;
  public static final int DETENER = 51;
  public static final int EQUAL = 24;
  public static final int PROC_PRINTLN = 37;
  public static final int TINNY = 42;
  public static final int CHAR = 8;
  public static final int BOOLEAN = 7;
  public static final int BTHAN = 28;
  public static final int PROC_ASIGNAR_HABILIDAD = 79;
  public static final int DIV = 34;
  public static final int FUNC_DISMINUIR = 72;
  public static final int KW_FLOAT = 17;
  public static final int FUNC_AUMENTAR = 71;
  public static final int INT = 2;
  public static final int NEQUAL = 25;
  public static final int ENULL = 30;
  public static final int EOF = 0;
  public static final int MIENTRAS = 49;
  public static final int LTHAN = 26;
  public static final int AUMENTAR = 54;
  public static final int CREAR_ARMA = 41;
  public static final int FUNC_GET_INT = 70;
  public static final int MINUS = 31;
  public static final int KW_LONG = 18;
  public static final int OR = 21;
  public static final int PROC_ASIGNAR_PASO = 75;
  public static final int error = 1;
  public static final int P2 = 12;
  public static final int P1 = 11;
  public static final int KW_CHAR = 16;
  public static final int HEAVY = 46;
  public static final int KW_STRING = 14;
  public static final int ID = 3;
  public static final int LETHAN = 27;
  public static final int ENTONCES = 60;
  public static final int PAUSAR = 52;
  public static final int PROC_AVANZAR = 77;
  public static final int PROC_ASIGNAR_ARMA = 74;
  public static final int OTRO_CASO = 61;
  public static final int FUNC_BORDE_TABLERO = 65;
  public static final int STRING = 36;
  public static final int BE = 6;
  public static final int BD = 4;
  public static final int BC = 5;
  public static final int AND = 22;
  public static final int HIGHT = 45;
  public static final int FIN_MIENTRAS = 50;
  public static final int XOR = 20;
}

