
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 25 23:46:15 CST 2013
//----------------------------------------------------

package compiler.lvl;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ESPACIOS_TAG2 = 5;
  public static final int ANY = 35;
  public static final int ESPACIOS_TAG1 = 4;
  public static final int DANIO_TAG2 = 27;
  public static final int DANIO_TAG1 = 26;
  public static final int EXTIENDE_TAG2 = 23;
  public static final int EXTIENDE_TAG1 = 22;
  public static final int FIN_TAG2 = 19;
  public static final int ESPACIO_TAG2 = 9;
  public static final int Y_TAG2 = 42;
  public static final int FIN_TAG1 = 18;
  public static final int ESPACIO_TAG1 = 8;
  public static final int Y_TAG1 = 41;
  public static final int INT = 36;
  public static final int MAGIA_TAG2 = 31;
  public static final int CURA_TAG2 = 29;
  public static final int CURA_TAG1 = 28;
  public static final int MAGIA_TAG1 = 30;
  public static final int IMPORTAR_TAG2 = 3;
  public static final int IMPORTAR_TAG1 = 2;
  public static final int ESPECIAL_TAG2 = 13;
  public static final int ESPECIAL_TAG1 = 12;
  public static final int ESTRUCTURA_TAG2 = 44;
  public static final int ENEMIGO_TAG2 = 21;
  public static final int ESTRUCTURA_TAG1 = 43;
  public static final int INVENCIBLE_TAG2 = 33;
  public static final int ENEMIGO_TAG1 = 20;
  public static final int INVENCIBLE_TAG1 = 32;
  public static final int EOF = 0;
  public static final int BOOLEAN = 34;
  public static final int NOMBRE_TAG2 = 11;
  public static final int error = 1;
  public static final int NOMBRE_TAG1 = 10;
  public static final int INICIO_TAG2 = 17;
  public static final int INICIO_TAG1 = 16;
  public static final int TAMANIO_TAG2 = 38;
  public static final int TAMANIO_TAG1 = 37;
  public static final int PASABLE_TAG2 = 15;
  public static final int PASABLE_TAG1 = 14;
  public static final int NIVEL_TAG2 = 7;
  public static final int X_TAG2 = 40;
  public static final int NIVEL_TAG1 = 6;
  public static final int X_TAG1 = 39;
  public static final int TIPO_TAG2 = 48;
  public static final int TIPO_TAG1 = 47;
  public static final int CASILLA_TAG2 = 46;
  public static final int CASILLA_TAG1 = 45;
  public static final int IMAGEN_TAG2 = 25;
  public static final int IMAGEN_TAG1 = 24;
  public static final int PERSONAJE_TAG2 = 50;
  public static final int PERSONAJE_TAG1 = 49;
}

