
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 26 16:17:30 CST 2013
//----------------------------------------------------

package compiler.psj;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int COSTO_MAGICO = 11;
  public static final int INT = 2;
  public static final int FINALIZAR = 5;
  public static final int COLON = 12;
  public static final int INICIAR = 4;
  public static final int EOF = 0;
  public static final int MAGIA = 9;
  public static final int FUERZA = 8;
  public static final int ID = 3;
  public static final int error = 1;
  public static final int FUERZA_MAGICA = 10;
  public static final int NOMBRE = 6;
  public static final int VIDA = 7;
}

